server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/secondhand?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: SQLjx1413
    driver-class-name: com.mysql.cj.jdbc.Driver

mapper:
  mappers: com.szqz.service.GeneralDAO
  not-empty: false
  identity: mysql
  # cn.hy.hyerp.erp.common.dal.BaseDao

mybatis:
    # 自动扫描
    type-aliases-package: com.szqz.entity
    configuration:
      # 打开延迟加载 的开关
      lazy-loading-enabled: true
      # 将积极加载改为消极加载即按需要加载
      aggressive-lazy-loading: false
      # 开启二级缓存
      cache-enabled: true
      # 支持驼峰命名法
      map-underscore-to-camel-case: true
    mapper-locations: classpath:mapper/*.xml